language: ruby
rvm:
  - 2.4.0
before_script:
  - bundle exec hanami db prepare
script:
  - bundle exec rake
services:
  - postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: YOUR_SECURE_KEY
  app:
    develop: YOUR_DEVELOPMENT_APP
    master: YOUR_PRODUCTION_APP
  on:
    repo: YOUR_GITHUB_REPO
  run:
    - "bundle exec hanami db prepare"